# Dockerfile to build SBaaS container images
# Based on Ubuntu

# Set the base image
FROM dmccloskey/python3cobrapy:latest

# File Author / Maintainer
MAINTAINER Douglas McCloskey <dmccloskey87@gmail.com

# Set several environmental variables that will be later removed
ENV GIT_USERNAME dmccloskey
ENV GIT_PASSWORD 18dglass
ENV GIT_ACCOUNT dmccloskey
ENV GIT_BRANCH master

#curl -sL --user "${GIT_USERNAME}:${GIT_PASSWORD}" https://github.com/$account/$repo/tarball/$tag_name > tarball.tar

# Install SBaaS modules from github
USER root
WORKDIR /usr/local
RUN mkdir SBaaS
WORKDIR /usr/local/SBaaS

# component-contribution
RUN curl -sL --user "${GIT_USERNAME}:${GIT_PASSWORD}" https://github.com/$GIT_ACCOUNT/component-contribution/archive/$GIT_BRANCH.zip > $GIT_BRANCH.zip \
	 && unzip $GIT_BRANCH.zip \ 
	 && mv component-contribution-$GIT_BRANCH component-contribution \
	 && rm $GIT_BRANCH.zip

# ddt_python
RUN curl -sL --user "${GIT_USERNAME}:${GIT_PASSWORD}" https://github.com/$GIT_ACCOUNT/ddt_python/archive/$GIT_BRANCH.zip > $GIT_BRANCH.zip \
	 && unzip $GIT_BRANCH.zip \ 
	 && mv ddt_python-$GIT_BRANCH ddt_python \
	 && rm $GIT_BRANCH.zip

# genomeScale_MFA
RUN curl -sL --user "${GIT_USERNAME}:${GIT_PASSWORD}" https://github.com/$GIT_ACCOUNT/genomeScale_MFA/archive/$GIT_BRANCH.zip > $GIT_BRANCH.zip \
	 && unzip $GIT_BRANCH.zip \ 
	 && mv genomeScale_MFA-$GIT_BRANCH genomeScale_MFA \
	 && rm $GIT_BRANCH.zip

# genomeScale_MFA_INCA
RUN curl -sL --user "${GIT_USERNAME}:${GIT_PASSWORD}" https://github.com/$GIT_ACCOUNT/genomeScale_MFA_INCA/archive/$GIT_BRANCH.zip > $GIT_BRANCH.zip \
	 && unzip $GIT_BRANCH.zip \ 
	 && mv genomeScale_MFA_INCA-$GIT_BRANCH genomeScale_MFA_INCA \
	 && rm $GIT_BRANCH.zip

# genomeScale_MFA_model
RUN curl -sL --user "${GIT_USERNAME}:${GIT_PASSWORD}" https://github.com/$GIT_ACCOUNT/genomeScale_MFA_model/archive/$GIT_BRANCH.zip > $GIT_BRANCH.zip \
	 && unzip $GIT_BRANCH.zip \ 
	 && mv genomeScale_MFA_model-$GIT_BRANCH genomeScale_MFA_model \
	 && rm $GIT_BRANCH.zip

# io_utilities
RUN curl -sL --user "${GIT_USERNAME}:${GIT_PASSWORD}" https://github.com/$GIT_ACCOUNT/io_utilities/archive/$GIT_BRANCH.zip > $GIT_BRANCH.zip \
	 && unzip $GIT_BRANCH.zip \ 
	 && mv io_utilities-$GIT_BRANCH io_utilities \
	 && rm $GIT_BRANCH.zip

# listDict
RUN curl -sL --user "${GIT_USERNAME}:${GIT_PASSWORD}" https://github.com/$GIT_ACCOUNT/listDict/archive/$GIT_BRANCH.zip > $GIT_BRANCH.zip \
	 && unzip $GIT_BRANCH.zip \ 
	 && mv listDict-$GIT_BRANCH listDict \
	 && rm $GIT_BRANCH.zip

# matplotlib_utilities
RUN curl -sL --user "${GIT_USERNAME}:${GIT_PASSWORD}" https://github.com/$GIT_ACCOUNT/matplotlib_utilities/archive/$GIT_BRANCH.zip > $GIT_BRANCH.zip \
	 && unzip $GIT_BRANCH.zip \ 
	 && mv matplotlib_utilities-$GIT_BRANCH matplotlib_utilities \
	 && rm $GIT_BRANCH.zip

# MDV_utilities
RUN curl -sL --user "${GIT_USERNAME}:${GIT_PASSWORD}" https://github.com/$GIT_ACCOUNT/MDV_utilities/archive/$GIT_BRANCH.zip > $GIT_BRANCH.zip \
	 && unzip $GIT_BRANCH.zip \ 
	 && mv MDV_utilities-$GIT_BRANCH MDV_utilities \
	 && rm $GIT_BRANCH.zip

# molmass
RUN curl -sL --user "${GIT_USERNAME}:${GIT_PASSWORD}" https://github.com/$GIT_ACCOUNT/molmass/archive/$GIT_BRANCH.zip > $GIT_BRANCH.zip \
	 && unzip $GIT_BRANCH.zip \ 
	 && mv molmass-$GIT_BRANCH molmass \
	 && rm $GIT_BRANCH.zip

# MS_utilities
RUN curl -sL --user "${GIT_USERNAME}:${GIT_PASSWORD}" https://github.com/$GIT_ACCOUNT/MS_utilities/archive/$GIT_BRANCH.zip > $GIT_BRANCH.zip \
	 && unzip $GIT_BRANCH.zip \ 
	 && mv MS_utilities-$GIT_BRANCH MS_utilities \
	 && rm $GIT_BRANCH.zip

# physiology_analysis
RUN curl -sL --user "${GIT_USERNAME}:${GIT_PASSWORD}" https://github.com/$GIT_ACCOUNT/physiology_analysis/archive/$GIT_BRANCH.zip > $GIT_BRANCH.zip \
	 && unzip $GIT_BRANCH.zip \ 
	 && mv physiology_analysis-$GIT_BRANCH physiology_analysis \
	 && rm $GIT_BRANCH.zip

# python_statistics
RUN curl -sL --user "${GIT_USERNAME}:${GIT_PASSWORD}" https://github.com/$GIT_ACCOUNT/python_statistics/archive/$GIT_BRANCH.zip > $GIT_BRANCH.zip \
	 && unzip $GIT_BRANCH.zip \ 
	 && mv python_statistics-$GIT_BRANCH python_statistics \
	 && rm $GIT_BRANCH.zip

# quantification_analysis
RUN curl -sL --user "${GIT_USERNAME}:${GIT_PASSWORD}" https://github.com/$GIT_ACCOUNT/quantification_analysis/archive/$GIT_BRANCH.zip > $GIT_BRANCH.zip \
	 && unzip $GIT_BRANCH.zip \ 
	 && mv quantification_analysis-$GIT_BRANCH quantification_analysis \
	 && rm $GIT_BRANCH.zip

# r_statistics
RUN curl -sL --user "${GIT_USERNAME}:${GIT_PASSWORD}" https://github.com/$GIT_ACCOUNT/r_statistics/archive/$GIT_BRANCH.zip > $GIT_BRANCH.zip \
	 && unzip $GIT_BRANCH.zip \ 
	 && mv r_statistics-$GIT_BRANCH r_statistics \
	 && rm $GIT_BRANCH.zip

# SBaaS_ale
RUN curl -sL --user "${GIT_USERNAME}:${GIT_PASSWORD}" https://github.com/$GIT_ACCOUNT/SBaaS_ale/archive/$GIT_BRANCH.zip > $GIT_BRANCH.zip \
	 && unzip $GIT_BRANCH.zip \ 
	 && mv SBaaS_ale-$GIT_BRANCH SBaaS_ale \
	 && rm $GIT_BRANCH.zip

# SBaaS_base
RUN curl -sL --user "${GIT_USERNAME}:${GIT_PASSWORD}" https://github.com/$GIT_ACCOUNT/SBaaS_base/archive/$GIT_BRANCH.zip > $GIT_BRANCH.zip \
	 && unzip $GIT_BRANCH.zip \ 
	 && mv SBaaS_base-$GIT_BRANCH SBaaS_base \
	 && rm $GIT_BRANCH.zip

# SBaaS_COBRA
RUN curl -sL --user "${GIT_USERNAME}:${GIT_PASSWORD}" https://github.com/$GIT_ACCOUNT/SBaaS_COBRA/archive/$GIT_BRANCH.zip > $GIT_BRANCH.zip \
	 && unzip $GIT_BRANCH.zip \ 
	 && mv SBaaS_COBRA-$GIT_BRANCH SBaaS_COBRA \
	 && rm $GIT_BRANCH.zip

# SBaaS_database
RUN curl -sL --user "${GIT_USERNAME}:${GIT_PASSWORD}" https://github.com/$GIT_ACCOUNT/SBaaS_database/archive/$GIT_BRANCH.zip > $GIT_BRANCH.zip \
	 && unzip $GIT_BRANCH.zip \ 
	 && mv SBaaS_database-$GIT_BRANCH SBaaS_database \
	 && rm $GIT_BRANCH.zip

# SBaaS_dataPreProcessing
RUN curl -sL --user "${GIT_USERNAME}:${GIT_PASSWORD}" https://github.com/$GIT_ACCOUNT/SBaaS_dataPreProcessing/archive/$GIT_BRANCH.zip > $GIT_BRANCH.zip \
	 && unzip $GIT_BRANCH.zip \ 
	 && mv SBaaS_dataPreProcessing-$GIT_BRANCH SBaaS_dataPreProcessing \
	 && rm $GIT_BRANCH.zip

# SBaaS_isotopomer
RUN curl -sL --user "${GIT_USERNAME}:${GIT_PASSWORD}" https://github.com/$GIT_ACCOUNT/SBaaS_isotopomer/archive/$GIT_BRANCH.zip > $GIT_BRANCH.zip \
	 && unzip $GIT_BRANCH.zip \ 
	 && mv SBaaS_isotopomer-$GIT_BRANCH SBaaS_isotopomer \
	 && rm $GIT_BRANCH.zip

# SBaaS_LIMS
RUN curl -sL --user "${GIT_USERNAME}:${GIT_PASSWORD}" https://github.com/$GIT_ACCOUNT/SBaaS_LIMS/archive/$GIT_BRANCH.zip > $GIT_BRANCH.zip \
	 && unzip $GIT_BRANCH.zip \ 
	 && mv SBaaS_LIMS-$GIT_BRANCH SBaaS_LIMS \
	 && rm $GIT_BRANCH.zip

# SBaaS_MFA
RUN curl -sL --user "${GIT_USERNAME}:${GIT_PASSWORD}" https://github.com/$GIT_ACCOUNT/SBaaS_MFA/archive/$GIT_BRANCH.zip > $GIT_BRANCH.zip \
	 && unzip $GIT_BRANCH.zip \ 
	 && mv SBaaS_MFA-$GIT_BRANCH SBaaS_MFA \
	 && rm $GIT_BRANCH.zip

# SBaaS_models
RUN curl -sL --user "${GIT_USERNAME}:${GIT_PASSWORD}" https://github.com/$GIT_ACCOUNT/SBaaS_models/archive/$GIT_BRANCH.zip > $GIT_BRANCH.zip \
	 && unzip $GIT_BRANCH.zip \ 
	 && mv SBaaS_models-$GIT_BRANCH SBaaS_models \
	 && rm $GIT_BRANCH.zip

# SBaaS_physiology
RUN curl -sL --user "${GIT_USERNAME}:${GIT_PASSWORD}" https://github.com/$GIT_ACCOUNT/SBaaS_physiology/archive/$GIT_BRANCH.zip > $GIT_BRANCH.zip \
	 && unzip $GIT_BRANCH.zip \ 
	 && mv SBaaS_physiology-$GIT_BRANCH SBaaS_physiology \
	 && rm $GIT_BRANCH.zip

# SBaaS_quantification
RUN curl -sL --user "${GIT_USERNAME}:${GIT_PASSWORD}" https://github.com/$GIT_ACCOUNT/SBaaS_quantification/archive/$GIT_BRANCH.zip > $GIT_BRANCH.zip \
	 && unzip $GIT_BRANCH.zip \ 
	 && mv SBaaS_quantification-$GIT_BRANCH SBaaS_quantification \
	 && rm $GIT_BRANCH.zip

# SBaaS_resequencing
RUN curl -sL --user "${GIT_USERNAME}:${GIT_PASSWORD}" https://github.com/$GIT_ACCOUNT/SBaaS_resequencing/archive/$GIT_BRANCH.zip > $GIT_BRANCH.zip \
	 && unzip $GIT_BRANCH.zip \ 
	 && mv SBaaS_resequencing-$GIT_BRANCH SBaaS_resequencing \
	 && rm $GIT_BRANCH.zip

# SBaaS_rnasequencing
RUN curl -sL --user "${GIT_USERNAME}:${GIT_PASSWORD}" https://github.com/$GIT_ACCOUNT/SBaaS_rnasequencing/archive/$GIT_BRANCH.zip > $GIT_BRANCH.zip \
	 && unzip $GIT_BRANCH.zip \ 
	 && mv SBaaS_rnasequencing-$GIT_BRANCH SBaaS_rnasequencing \
	 && rm $GIT_BRANCH.zip

# SBaaS_statistics
RUN curl -sL --user "${GIT_USERNAME}:${GIT_PASSWORD}" https://github.com/$GIT_ACCOUNT/SBaaS_statistics/archive/$GIT_BRANCH.zip > $GIT_BRANCH.zip \
	 && unzip $GIT_BRANCH.zip \ 
	 && mv SBaaS_statistics-$GIT_BRANCH SBaaS_statistics \
	 && rm $GIT_BRANCH.zip

# SBaaS_thermodynamics
RUN curl -sL --user "${GIT_USERNAME}:${GIT_PASSWORD}" https://github.com/$GIT_ACCOUNT/SBaaS_thermodynamics/archive/$GIT_BRANCH.zip > $GIT_BRANCH.zip \
	 && unzip $GIT_BRANCH.zip \ 
	 && mv SBaaS_thermodynamics-$GIT_BRANCH SBaaS_thermodynamics \
	 && rm $GIT_BRANCH.zip

# SBaaS_visualization
RUN curl -sL --user "${GIT_USERNAME}:${GIT_PASSWORD}" https://github.com/$GIT_ACCOUNT/SBaaS_visualization/archive/$GIT_BRANCH.zip > $GIT_BRANCH.zip \
	 && unzip $GIT_BRANCH.zip \ 
	 && mv SBaaS_visualization-$GIT_BRANCH SBaaS_visualization \
	 && rm $GIT_BRANCH.zip

# SBaaS_webServer
RUN curl -sL --user "${GIT_USERNAME}:${GIT_PASSWORD}" https://github.com/$GIT_ACCOUNT/SBaaS_webServer/archive/$GIT_BRANCH.zip > $GIT_BRANCH.zip \
	 && unzip $GIT_BRANCH.zip \ 
	 && mv SBaaS_webServer-$GIT_BRANCH SBaaS_webServer \
	 && rm $GIT_BRANCH.zip

# sequencing_analysis
RUN curl -sL --user "${GIT_USERNAME}:${GIT_PASSWORD}" https://github.com/$GIT_ACCOUNT/sequencing_analysis/archive/$GIT_BRANCH.zip > $GIT_BRANCH.zip \
	 && unzip $GIT_BRANCH.zip \ 
	 && mv sequencing_analysis-$GIT_BRANCH sequencing_analysis \
	 && rm $GIT_BRANCH.zip

# sequencing_utilities
RUN curl -sL --user "${GIT_USERNAME}:${GIT_PASSWORD}" https://github.com/$GIT_ACCOUNT/sequencing_utilities/archive/$GIT_BRANCH.zip > $GIT_BRANCH.zip \
	 && unzip $GIT_BRANCH.zip \ 
	 && mv sequencing_utilities-$GIT_BRANCH sequencing_utilities \
	 && rm $GIT_BRANCH.zip

# thermodynamics
RUN curl -sL --user "${GIT_USERNAME}:${GIT_PASSWORD}" https://github.com/$GIT_ACCOUNT/thermodynamics/archive/$GIT_BRANCH.zip > $GIT_BRANCH.zip \
	 && unzip $GIT_BRANCH.zip \ 
	 && mv thermodynamics-$GIT_BRANCH thermodynamics \
	 && rm $GIT_BRANCH.zip

# remove the environmental variables
RUN env --unset=GIT_USERNAME \
	&& env --unset=GIT_PASSWORD \
	&& env --unset=GIT_ACCOUNT \
	&& env --unset=GIT_BRANCH

EXPOSE 8080
WORKDIR $HOME
USER user