ALTER TABLE metabolomics_experiment RENAME COLUMN metabolomics_sample_name TO sample_name;
ALTER TABLE metabolomics_experiment RENAME TO experiment;
ALTER TABLE metabolomics_experimentor RENAME TO experimentor;
ALTER TABLE metabolomics_experimentor_list RENAME TO experimentor_list;
ALTER TABLE metabolomics_experimentor_id2name RENAME TO experimentor_id2name;
ALTER TABLE metabolomics_calibrator RENAME TO calibrator;
ALTER TABLE metabolomics_sample RENAME TO sample;
ALTER TABLE metabolomics_standards RENAME TO standards;
ALTER TABLE is_storage RENAME TO internal_standard_storage;
ALTER TABLE metabolomics_is RENAME TO internal_standard;
ALTER TABLE experiment RENAME COLUMN metabolomics_is_id TO internal_standard_id;
ALTER TABLE experiment RENAME COLUMN metabolomics_experimentor_id TO experimentor_id;